source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.1'

target 'TrueGrowthSF' do
pod 'AFNetworking', '~> 3.0'
end

source 'https://github.com/CocoaPods/Specs.git'
target ‘TrueGrowthSF’ do
pod 'AWSCore'
pod 'AWSAutoScaling'
pod 'AWSCloudWatch'
pod 'AWSDynamoDB'
pod 'AWSEC2'
pod 'AWSElasticLoadBalancing'
pod 'AWSKinesis'
pod 'AWSLambda'
pod 'AWSMachineLearning'
pod 'AWSMobileAnalytics'
pod 'AWSS3'
pod 'AWSSES'
pod 'AWSSimpleDB'
pod 'AWSSNS'
pod 'AWSSQS'
pod 'AWSCognito'
end